//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("POC_TAXModel", "FK_TAX_ORDERTYPE", "ORDERTYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POC.DataBase.ORDERTYPE), "TAX", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POC.DataBase.TAX), true)]
[assembly: EdmRelationshipAttribute("POC_TAXModel", "FK_TAXCOND_TAX", "TAX", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POC.DataBase.TAX), "TAXCOND", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POC.DataBase.TAXCOND), true)]

#endregion

namespace POC.DataBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class POC_TAXEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new POC_TAXEntities object using the connection string found in the 'POC_TAXEntities' section of the application configuration file.
        /// </summary>
        public POC_TAXEntities() : base("name=POC_TAXEntities", "POC_TAXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new POC_TAXEntities object.
        /// </summary>
        public POC_TAXEntities(string connectionString) : base(connectionString, "POC_TAXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new POC_TAXEntities object.
        /// </summary>
        public POC_TAXEntities(EntityConnection connection) : base(connection, "POC_TAXEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ORDERTYPE> ORDERTYPE
        {
            get
            {
                if ((_ORDERTYPE == null))
                {
                    _ORDERTYPE = base.CreateObjectSet<ORDERTYPE>("ORDERTYPE");
                }
                return _ORDERTYPE;
            }
        }
        private ObjectSet<ORDERTYPE> _ORDERTYPE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TAX> TAX
        {
            get
            {
                if ((_TAX == null))
                {
                    _TAX = base.CreateObjectSet<TAX>("TAX");
                }
                return _TAX;
            }
        }
        private ObjectSet<TAX> _TAX;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TAXCOND> TAXCOND
        {
            get
            {
                if ((_TAXCOND == null))
                {
                    _TAXCOND = base.CreateObjectSet<TAXCOND>("TAXCOND");
                }
                return _TAXCOND;
            }
        }
        private ObjectSet<TAXCOND> _TAXCOND;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ORDERTYPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToORDERTYPE(ORDERTYPE oRDERTYPE)
        {
            base.AddObject("ORDERTYPE", oRDERTYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAX EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAX(TAX tAX)
        {
            base.AddObject("TAX", tAX);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TAXCOND EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTAXCOND(TAXCOND tAXCOND)
        {
            base.AddObject("TAXCOND", tAXCOND);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="POC_TAXModel", Name="ORDERTYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ORDERTYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ORDERTYPE object.
        /// </summary>
        /// <param name="oRDERTYPE_ID">Initial value of the ORDERTYPE_ID property.</param>
        /// <param name="oRDERTYPE_BUSINESSUNITKEY">Initial value of the ORDERTYPE_BUSINESSUNITKEY property.</param>
        public static ORDERTYPE CreateORDERTYPE(global::System.Int32 oRDERTYPE_ID, global::System.String oRDERTYPE_BUSINESSUNITKEY)
        {
            ORDERTYPE oRDERTYPE = new ORDERTYPE();
            oRDERTYPE.ORDERTYPE_ID = oRDERTYPE_ID;
            oRDERTYPE.ORDERTYPE_BUSINESSUNITKEY = oRDERTYPE_BUSINESSUNITKEY;
            return oRDERTYPE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ORDERTYPE_ID
        {
            get
            {
                return _ORDERTYPE_ID;
            }
            set
            {
                if (_ORDERTYPE_ID != value)
                {
                    OnORDERTYPE_IDChanging(value);
                    ReportPropertyChanging("ORDERTYPE_ID");
                    _ORDERTYPE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ORDERTYPE_ID");
                    OnORDERTYPE_IDChanged();
                }
            }
        }
        private global::System.Int32 _ORDERTYPE_ID;
        partial void OnORDERTYPE_IDChanging(global::System.Int32 value);
        partial void OnORDERTYPE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_TITLE
        {
            get
            {
                return _ORDERTYPE_TITLE;
            }
            set
            {
                OnORDERTYPE_TITLEChanging(value);
                ReportPropertyChanging("ORDERTYPE_TITLE");
                _ORDERTYPE_TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_TITLE");
                OnORDERTYPE_TITLEChanged();
            }
        }
        private global::System.String _ORDERTYPE_TITLE;
        partial void OnORDERTYPE_TITLEChanging(global::System.String value);
        partial void OnORDERTYPE_TITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_DESCRIPTION
        {
            get
            {
                return _ORDERTYPE_DESCRIPTION;
            }
            set
            {
                OnORDERTYPE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("ORDERTYPE_DESCRIPTION");
                _ORDERTYPE_DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_DESCRIPTION");
                OnORDERTYPE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _ORDERTYPE_DESCRIPTION;
        partial void OnORDERTYPE_DESCRIPTIONChanging(global::System.String value);
        partial void OnORDERTYPE_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_XMLFORM
        {
            get
            {
                return _ORDERTYPE_XMLFORM;
            }
            set
            {
                OnORDERTYPE_XMLFORMChanging(value);
                ReportPropertyChanging("ORDERTYPE_XMLFORM");
                _ORDERTYPE_XMLFORM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_XMLFORM");
                OnORDERTYPE_XMLFORMChanged();
            }
        }
        private global::System.String _ORDERTYPE_XMLFORM;
        partial void OnORDERTYPE_XMLFORMChanging(global::System.String value);
        partial void OnORDERTYPE_XMLFORMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_BUSINESSUNITKEY
        {
            get
            {
                return _ORDERTYPE_BUSINESSUNITKEY;
            }
            set
            {
                OnORDERTYPE_BUSINESSUNITKEYChanging(value);
                ReportPropertyChanging("ORDERTYPE_BUSINESSUNITKEY");
                _ORDERTYPE_BUSINESSUNITKEY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ORDERTYPE_BUSINESSUNITKEY");
                OnORDERTYPE_BUSINESSUNITKEYChanged();
            }
        }
        private global::System.String _ORDERTYPE_BUSINESSUNITKEY;
        partial void OnORDERTYPE_BUSINESSUNITKEYChanging(global::System.String value);
        partial void OnORDERTYPE_BUSINESSUNITKEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ORDERTYPE_GDCCID
        {
            get
            {
                return _ORDERTYPE_GDCCID;
            }
            set
            {
                OnORDERTYPE_GDCCIDChanging(value);
                ReportPropertyChanging("ORDERTYPE_GDCCID");
                _ORDERTYPE_GDCCID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDERTYPE_GDCCID");
                OnORDERTYPE_GDCCIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ORDERTYPE_GDCCID;
        partial void OnORDERTYPE_GDCCIDChanging(Nullable<global::System.Int32> value);
        partial void OnORDERTYPE_GDCCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ORDERTYPE_NEEDSLOGIN
        {
            get
            {
                return _ORDERTYPE_NEEDSLOGIN;
            }
            set
            {
                OnORDERTYPE_NEEDSLOGINChanging(value);
                ReportPropertyChanging("ORDERTYPE_NEEDSLOGIN");
                _ORDERTYPE_NEEDSLOGIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDERTYPE_NEEDSLOGIN");
                OnORDERTYPE_NEEDSLOGINChanged();
            }
        }
        private Nullable<global::System.Boolean> _ORDERTYPE_NEEDSLOGIN;
        partial void OnORDERTYPE_NEEDSLOGINChanging(Nullable<global::System.Boolean> value);
        partial void OnORDERTYPE_NEEDSLOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ORDERTYPE_CREATEDATE
        {
            get
            {
                return _ORDERTYPE_CREATEDATE;
            }
            set
            {
                OnORDERTYPE_CREATEDATEChanging(value);
                ReportPropertyChanging("ORDERTYPE_CREATEDATE");
                _ORDERTYPE_CREATEDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDERTYPE_CREATEDATE");
                OnORDERTYPE_CREATEDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ORDERTYPE_CREATEDATE;
        partial void OnORDERTYPE_CREATEDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnORDERTYPE_CREATEDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_PDFFORM_URL
        {
            get
            {
                return _ORDERTYPE_PDFFORM_URL;
            }
            set
            {
                OnORDERTYPE_PDFFORM_URLChanging(value);
                ReportPropertyChanging("ORDERTYPE_PDFFORM_URL");
                _ORDERTYPE_PDFFORM_URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_PDFFORM_URL");
                OnORDERTYPE_PDFFORM_URLChanged();
            }
        }
        private global::System.String _ORDERTYPE_PDFFORM_URL;
        partial void OnORDERTYPE_PDFFORM_URLChanging(global::System.String value);
        partial void OnORDERTYPE_PDFFORM_URLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_REDIRECT
        {
            get
            {
                return _ORDERTYPE_REDIRECT;
            }
            set
            {
                OnORDERTYPE_REDIRECTChanging(value);
                ReportPropertyChanging("ORDERTYPE_REDIRECT");
                _ORDERTYPE_REDIRECT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_REDIRECT");
                OnORDERTYPE_REDIRECTChanged();
            }
        }
        private global::System.String _ORDERTYPE_REDIRECT;
        partial void OnORDERTYPE_REDIRECTChanging(global::System.String value);
        partial void OnORDERTYPE_REDIRECTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_ORDER_SCHEMA
        {
            get
            {
                return _ORDERTYPE_ORDER_SCHEMA;
            }
            set
            {
                OnORDERTYPE_ORDER_SCHEMAChanging(value);
                ReportPropertyChanging("ORDERTYPE_ORDER_SCHEMA");
                _ORDERTYPE_ORDER_SCHEMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_ORDER_SCHEMA");
                OnORDERTYPE_ORDER_SCHEMAChanged();
            }
        }
        private global::System.String _ORDERTYPE_ORDER_SCHEMA;
        partial void OnORDERTYPE_ORDER_SCHEMAChanging(global::System.String value);
        partial void OnORDERTYPE_ORDER_SCHEMAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDERTYPE_ORDER_ROOTNAME
        {
            get
            {
                return _ORDERTYPE_ORDER_ROOTNAME;
            }
            set
            {
                OnORDERTYPE_ORDER_ROOTNAMEChanging(value);
                ReportPropertyChanging("ORDERTYPE_ORDER_ROOTNAME");
                _ORDERTYPE_ORDER_ROOTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ORDERTYPE_ORDER_ROOTNAME");
                OnORDERTYPE_ORDER_ROOTNAMEChanged();
            }
        }
        private global::System.String _ORDERTYPE_ORDER_ROOTNAME;
        partial void OnORDERTYPE_ORDER_ROOTNAMEChanging(global::System.String value);
        partial void OnORDERTYPE_ORDER_ROOTNAMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("POC_TAXModel", "FK_TAX_ORDERTYPE", "TAX")]
        public EntityCollection<TAX> TAX
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAX>("POC_TAXModel.FK_TAX_ORDERTYPE", "TAX");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAX>("POC_TAXModel.FK_TAX_ORDERTYPE", "TAX", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="POC_TAXModel", Name="TAX")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAX : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TAX object.
        /// </summary>
        /// <param name="tAX_ID">Initial value of the TAX_ID property.</param>
        public static TAX CreateTAX(global::System.Int32 tAX_ID)
        {
            TAX tAX = new TAX();
            tAX.TAX_ID = tAX_ID;
            return tAX;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TAX_ID
        {
            get
            {
                return _TAX_ID;
            }
            set
            {
                if (_TAX_ID != value)
                {
                    OnTAX_IDChanging(value);
                    ReportPropertyChanging("TAX_ID");
                    _TAX_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TAX_ID");
                    OnTAX_IDChanged();
                }
            }
        }
        private global::System.Int32 _TAX_ID;
        partial void OnTAX_IDChanging(global::System.Int32 value);
        partial void OnTAX_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TAX_ORDERTYPEID
        {
            get
            {
                return _TAX_ORDERTYPEID;
            }
            set
            {
                OnTAX_ORDERTYPEIDChanging(value);
                ReportPropertyChanging("TAX_ORDERTYPEID");
                _TAX_ORDERTYPEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_ORDERTYPEID");
                OnTAX_ORDERTYPEIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TAX_ORDERTYPEID;
        partial void OnTAX_ORDERTYPEIDChanging(Nullable<global::System.Int32> value);
        partial void OnTAX_ORDERTYPEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAX_NAME
        {
            get
            {
                return _TAX_NAME;
            }
            set
            {
                OnTAX_NAMEChanging(value);
                ReportPropertyChanging("TAX_NAME");
                _TAX_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAX_NAME");
                OnTAX_NAMEChanged();
            }
        }
        private global::System.String _TAX_NAME;
        partial void OnTAX_NAMEChanging(global::System.String value);
        partial void OnTAX_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAX_DESCRIPTION
        {
            get
            {
                return _TAX_DESCRIPTION;
            }
            set
            {
                OnTAX_DESCRIPTIONChanging(value);
                ReportPropertyChanging("TAX_DESCRIPTION");
                _TAX_DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAX_DESCRIPTION");
                OnTAX_DESCRIPTIONChanged();
            }
        }
        private global::System.String _TAX_DESCRIPTION;
        partial void OnTAX_DESCRIPTIONChanging(global::System.String value);
        partial void OnTAX_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TAX_DISCOUNT
        {
            get
            {
                return _TAX_DISCOUNT;
            }
            set
            {
                OnTAX_DISCOUNTChanging(value);
                ReportPropertyChanging("TAX_DISCOUNT");
                _TAX_DISCOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_DISCOUNT");
                OnTAX_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _TAX_DISCOUNT;
        partial void OnTAX_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnTAX_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TAX_VALUE
        {
            get
            {
                return _TAX_VALUE;
            }
            set
            {
                OnTAX_VALUEChanging(value);
                ReportPropertyChanging("TAX_VALUE");
                _TAX_VALUE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_VALUE");
                OnTAX_VALUEChanged();
            }
        }
        private Nullable<global::System.Double> _TAX_VALUE;
        partial void OnTAX_VALUEChanging(Nullable<global::System.Double> value);
        partial void OnTAX_VALUEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TAX_CHANNELID
        {
            get
            {
                return _TAX_CHANNELID;
            }
            set
            {
                OnTAX_CHANNELIDChanging(value);
                ReportPropertyChanging("TAX_CHANNELID");
                _TAX_CHANNELID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_CHANNELID");
                OnTAX_CHANNELIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TAX_CHANNELID;
        partial void OnTAX_CHANNELIDChanging(Nullable<global::System.Int32> value);
        partial void OnTAX_CHANNELIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAX_FORMITEMNAME
        {
            get
            {
                return _TAX_FORMITEMNAME;
            }
            set
            {
                OnTAX_FORMITEMNAMEChanging(value);
                ReportPropertyChanging("TAX_FORMITEMNAME");
                _TAX_FORMITEMNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAX_FORMITEMNAME");
                OnTAX_FORMITEMNAMEChanged();
            }
        }
        private global::System.String _TAX_FORMITEMNAME;
        partial void OnTAX_FORMITEMNAMEChanging(global::System.String value);
        partial void OnTAX_FORMITEMNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TAX_START_DATE
        {
            get
            {
                return _TAX_START_DATE;
            }
            set
            {
                OnTAX_START_DATEChanging(value);
                ReportPropertyChanging("TAX_START_DATE");
                _TAX_START_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_START_DATE");
                OnTAX_START_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _TAX_START_DATE;
        partial void OnTAX_START_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnTAX_START_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TAX_END_DATE
        {
            get
            {
                return _TAX_END_DATE;
            }
            set
            {
                OnTAX_END_DATEChanging(value);
                ReportPropertyChanging("TAX_END_DATE");
                _TAX_END_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAX_END_DATE");
                OnTAX_END_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _TAX_END_DATE;
        partial void OnTAX_END_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnTAX_END_DATEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("POC_TAXModel", "FK_TAX_ORDERTYPE", "ORDERTYPE")]
        public ORDERTYPE ORDERTYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDERTYPE>("POC_TAXModel.FK_TAX_ORDERTYPE", "ORDERTYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDERTYPE>("POC_TAXModel.FK_TAX_ORDERTYPE", "ORDERTYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ORDERTYPE> ORDERTYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ORDERTYPE>("POC_TAXModel.FK_TAX_ORDERTYPE", "ORDERTYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ORDERTYPE>("POC_TAXModel.FK_TAX_ORDERTYPE", "ORDERTYPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("POC_TAXModel", "FK_TAXCOND_TAX", "TAXCOND")]
        public EntityCollection<TAXCOND> TAXCOND
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAXCOND>("POC_TAXModel.FK_TAXCOND_TAX", "TAXCOND");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAXCOND>("POC_TAXModel.FK_TAXCOND_TAX", "TAXCOND", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="POC_TAXModel", Name="TAXCOND")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAXCOND : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TAXCOND object.
        /// </summary>
        /// <param name="tAXCOND_ID">Initial value of the TAXCOND_ID property.</param>
        public static TAXCOND CreateTAXCOND(global::System.Int32 tAXCOND_ID)
        {
            TAXCOND tAXCOND = new TAXCOND();
            tAXCOND.TAXCOND_ID = tAXCOND_ID;
            return tAXCOND;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TAXCOND_ID
        {
            get
            {
                return _TAXCOND_ID;
            }
            set
            {
                if (_TAXCOND_ID != value)
                {
                    OnTAXCOND_IDChanging(value);
                    ReportPropertyChanging("TAXCOND_ID");
                    _TAXCOND_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TAXCOND_ID");
                    OnTAXCOND_IDChanged();
                }
            }
        }
        private global::System.Int32 _TAXCOND_ID;
        partial void OnTAXCOND_IDChanging(global::System.Int32 value);
        partial void OnTAXCOND_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TAXCOND_TAXID
        {
            get
            {
                return _TAXCOND_TAXID;
            }
            set
            {
                OnTAXCOND_TAXIDChanging(value);
                ReportPropertyChanging("TAXCOND_TAXID");
                _TAXCOND_TAXID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAXCOND_TAXID");
                OnTAXCOND_TAXIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TAXCOND_TAXID;
        partial void OnTAXCOND_TAXIDChanging(Nullable<global::System.Int32> value);
        partial void OnTAXCOND_TAXIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAXCOND_FORMITEMNAME
        {
            get
            {
                return _TAXCOND_FORMITEMNAME;
            }
            set
            {
                OnTAXCOND_FORMITEMNAMEChanging(value);
                ReportPropertyChanging("TAXCOND_FORMITEMNAME");
                _TAXCOND_FORMITEMNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAXCOND_FORMITEMNAME");
                OnTAXCOND_FORMITEMNAMEChanged();
            }
        }
        private global::System.String _TAXCOND_FORMITEMNAME;
        partial void OnTAXCOND_FORMITEMNAMEChanging(global::System.String value);
        partial void OnTAXCOND_FORMITEMNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAXCOND_FORMITEMOP
        {
            get
            {
                return _TAXCOND_FORMITEMOP;
            }
            set
            {
                OnTAXCOND_FORMITEMOPChanging(value);
                ReportPropertyChanging("TAXCOND_FORMITEMOP");
                _TAXCOND_FORMITEMOP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAXCOND_FORMITEMOP");
                OnTAXCOND_FORMITEMOPChanged();
            }
        }
        private global::System.String _TAXCOND_FORMITEMOP;
        partial void OnTAXCOND_FORMITEMOPChanging(global::System.String value);
        partial void OnTAXCOND_FORMITEMOPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TAXCOND_FORMITEMVALUE
        {
            get
            {
                return _TAXCOND_FORMITEMVALUE;
            }
            set
            {
                OnTAXCOND_FORMITEMVALUEChanging(value);
                ReportPropertyChanging("TAXCOND_FORMITEMVALUE");
                _TAXCOND_FORMITEMVALUE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TAXCOND_FORMITEMVALUE");
                OnTAXCOND_FORMITEMVALUEChanged();
            }
        }
        private global::System.String _TAXCOND_FORMITEMVALUE;
        partial void OnTAXCOND_FORMITEMVALUEChanging(global::System.String value);
        partial void OnTAXCOND_FORMITEMVALUEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("POC_TAXModel", "FK_TAXCOND_TAX", "TAX")]
        public TAX TAX
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAX>("POC_TAXModel.FK_TAXCOND_TAX", "TAX").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAX>("POC_TAXModel.FK_TAXCOND_TAX", "TAX").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TAX> TAXReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAX>("POC_TAXModel.FK_TAXCOND_TAX", "TAX");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TAX>("POC_TAXModel.FK_TAXCOND_TAX", "TAX", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
